volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/grav
      o: bind
services:
  grav:
    build: ./
    ports:
      - 8080:80
    volumes:
      - grav-data:/var/www/html
  node:
    image: node:16
    volumes:
      - './grav/user/themes/custom:/usr/app'
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"