version: "3.9"
services:
  grav:
    build: ./
    ports:
      - 8080:80
    volumes:
      - ./grav:/var/www/html
  node:
    image: node:16
    volumes:
      - './grav/user/themes/custom:/usr/app'
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"