---
all:
  vars:
    env: local
    build_directory: "/Users/chloecorfmat/Documents/AE/Dev/sales/ansible/build"
    deploy_directory: "/Users/chloecorfmat/Documents/AE/Dev/sales/ansible/deploy"
  children:
    build:
      hosts:
        build:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    server:
      hosts:
        server:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3