---
all:
  vars:
    env: prod
    build_directory: "/Users/chloecorfmat/Documents/AE/Dev/sales/ansible/build"
    deploy_directory: "/opt/application/sales"
  children:
    build:
      hosts:
        build:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    server:
      hosts:
        server:
          ansible_host: 51.210.43.70
          ansible_port: 22
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3