- debug:
    msg:
      - "Start grav build"

- name: "Remove build directory"
  file:
    path: "{{ build_directory }}"
    state: absent

- name: "Create build directory"
  file:
    path: "{{ build_directory }}"
    state: directory
    mode: '0755'

- name: Clone repository
  git:
    repo: "{{ git_project }}"
    dest: "{{ build_directory }}"
    version: "{{ tag }}"

- name: Launch docker
  community.docker.docker_compose:
    project_src: "{{ build_directory }}"
    build: false

- name: Stop docker
  community.docker.docker_compose:
    project_src: "{{ build_directory }}"
    state: absent