title: 'Chloé Corfmat'
default_lang: fr
author:
  name: 'Chloé Corfmat'
  email: contact@chloecorfmat.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'Chloé Corfmat'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
